# Generated by Django 4.1.5 on 2023-01-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mangoApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('userId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('userPass', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='postuser',
            old_name='userId',
            new_name='adminId',
        ),
        migrations.RenameField(
            model_name='postuser',
            old_name='userPass',
            new_name='adminPass',
        ),
    ]
